#!/usr/bin/env python3
"""
Google Calendar & Tasks Assistant - Credential Setup Helper
This script helps you set up Google API credentials for the application.
"""

import os
import webbrowser
from pathlib import Path

def main():
    print("🔧 Google Calendar & Tasks Assistant - Setup Helper")
    print("=" * 60)
    
    # Check if secrets file exists
    secrets_path = Path(".streamlit/secrets.toml")
    if not secrets_path.exists():
        print("❌ Secrets file not found!")
        print("Please run this script from the project root directory.")
        return
    
    print("📋 Step-by-Step Setup Guide:")
    print()
    
    print("1️⃣  GOOGLE CLOUD CONSOLE SETUP")
    print("   We'll open Google Cloud Console for you...")
    
    input("   Press Enter to open Google Cloud Console...")
    webbrowser.open("https://console.cloud.google.com/")
    
    print()
    print("2️⃣  CREATE OR SELECT PROJECT")
    print("   - Create a new project or select an existing one")
    print("   - Note down your project name")
    
    input("   Press Enter when you've created/selected a project...")
    
    print()
    print("3️⃣  ENABLE APIS")
    print("   We'll open the API Library for you...")
    
    input("   Press Enter to open API Library...")
    webbrowser.open("https://console.cloud.google.com/apis/library")
    
    print()
    print("   📌 Enable these APIs:")
    print("   - Search for 'Google Calendar API' and enable it")
    print("   - Search for 'Google Tasks API' and enable it")
    
    input("   Press Enter when you've enabled both APIs...")
    
    print()
    print("4️⃣  CREATE OAUTH CREDENTIALS")
    print("   We'll open the Credentials page for you...")
    
    input("   Press Enter to open Credentials page...")
    webbrowser.open("https://console.cloud.google.com/apis/credentials")
    
    print()
    print("   📌 Create OAuth 2.0 Client ID:")
    print("   - Click 'Create Credentials' > 'OAuth 2.0 Client IDs'")
    print("   - Choose 'Web application'")
    print("   - Name: 'Calendar Tasks Assistant'")
    print("   - Authorized redirect URIs: http://localhost:8501")
    print("   - Click 'Create'")
    
    input("   Press Enter when you've created the OAuth client...")
    
    print()
    print("5️⃣  COPY CREDENTIALS")
    print("   Now you should see a popup with your credentials.")
    print("   Copy the Client ID and Client Secret.")
    print()
    
    # Get credentials from user
    client_id = input("   📋 Paste your Client ID here: ").strip()
    client_secret = input("   📋 Paste your Client Secret here: ").strip()
    
    if not client_id or not client_secret:
        print("❌ Invalid credentials provided!")
        return
    
    print()
    print("6️⃣  UPDATING CONFIGURATION")
    
    # Update secrets file
    secrets_content = f'''# Google API Credentials
CLIENT_ID = "{client_id}"
CLIENT_SECRET = "{client_secret}"
REDIRECT_URI = "http://localhost:8501"

# Generated by setup_credentials.py
# Date: {os.popen("date").read().strip()}
'''
    
    try:
        with open(secrets_path, 'w') as f:
            f.write(secrets_content)
        print("   ✅ Credentials saved successfully!")
    except Exception as e:
        print(f"   ❌ Error saving credentials: {e}")
        return
    
    print()
    print("7️⃣  READY TO RUN!")
    print("   Your app is now configured and ready to use.")
    print()
    print("   🚀 To start the app, run:")
    print("      python -m streamlit run app.py")
    print()
    print("   📝 Note: On first run, you'll need to:")
    print("   - Click the Google login link")
    print("   - Grant permissions for Calendar and Tasks access")
    print("   - You'll be redirected back to the app")
    print()
    print("✅ Setup complete! Enjoy your Calendar & Tasks Assistant!")

if __name__ == "__main__":
    main()
